#!/usr/bin/env python3
"""
fix_x2ap_ioc_compat.py

Reconcile the 3 X2AP "Outcome/InitiatingMessage" headers (modified by
fix_x2ap_compat_v2.py into a slim union) with the full IOC code generated by
asn1c-844f9ca in the matching .c files:

  * .c uses `struct X2AP_XXX__value`  (double-underscore tag)
  * .h had `struct X2AP_XXX_value`    (single-underscore tag)  -> restore __value
  * .c's asn_MBR rows reference EVERY procedure member in `choice.XXX`
  * .h only had the slim set of members OAI sources touch      -> add all members

Members are value types (X2AP_XXX_t Member;), consistent with the existing fix
style; offsetof() in the .c is unaffected by value vs pointer.

Usage: python3 fix_x2ap_ioc_compat.py
"""

import os
import re

DIR = "/home/kongbai/openairinterface5g/build-riscv/openair2/X2AP/MESSAGES"

FILES = [
    ("X2AP_InitiatingMessage.c", "X2AP_InitiatingMessage.h"),
    ("X2AP_SuccessfulOutcome.c", "X2AP_SuccessfulOutcome.h"),
    ("X2AP_UnsuccessfulOutcome.c", "X2AP_UnsuccessfulOutcome.h"),
]


def extract_members(c_path):
    text = open(os.path.join(DIR, c_path)).read()
    members = re.findall(r"choice\.(\w+)", text)
    # dedupe preserving order
    seen = set()
    out = []
    for m in members:
        if m not in seen:
            seen.add(m)
            out.append(m)
    return out


def fix_header(h_path, members):
    path = os.path.join(DIR, h_path)
    content = open(path).read()
    base = h_path[:-2]  # strip ".h" -> X2AP_InitiatingMessage

    # 1) restore double-underscore struct tag
    if f"typedef struct {base}_value {{" in content:
        content = content.replace(
            f"typedef struct {base}_value {{",
            f"typedef struct {base}__value {{",
        )
    elif f"typedef struct {base}__value {{" not in content:
        print(f"  !! {h_path}: struct tag not found")
        return False

    # 2) rebuild the union with all members
    union_pat = re.compile(
        rf"union {base}_value_u \{{.*?\}} choice;", re.S
    )
    members_txt = "".join(f"\t\tX2AP_{m}_t\t {m};\n" for m in members)
    new_union = (
        f"union {base}_value_u {{\n{members_txt}\t}} choice;"
    )
    if union_pat.search(content):
        content = union_pat.sub(new_union, content)
    else:
        print(f"  !! {h_path}: union block not found")
        return False

    # 3) put ALL member-type includes at the TOP include area (types must be
    #    declared before the union, which lives mid-file). Remove any stray
    #    copies (e.g. from a previous run) wherever they are.
    member_incs = {f"X2AP_{m}.h" for m in members}
    member_incs -= {f"X2AP_{m}.h" for m in members if not os.path.exists(os.path.join(DIR, f"X2AP_{m}.h"))}
    lines = content.split("\n")
    kept = []
    for line in lines:
        mm = re.match(r'\s*#include\s+"(X2AP_\w+\.h)"', line)
        if mm and mm.group(1) in member_incs:
            continue  # drop; re-inserted at top below
        kept.append(line)
    first_inc = next(i for i, l in enumerate(kept) if l.lstrip().startswith("#include"))
    insert_block = "".join(f'#include "{a}"\n' for a in sorted(member_incs)).rstrip("\n")
    kept.insert(first_inc + 1, insert_block)
    content = "\n".join(kept)

    open(path, "w").write(content)
    return True


def main():
    for c_path, h_path in FILES:
        members = extract_members(c_path)
        ok = fix_header(h_path, members)
        print(f"{h_path}: {len(members)} members -> {'OK' if ok else 'FAILED'}")
        if ok:
            print("  members: " + ", ".join(members[:8]) + (" ..." if len(members) > 8 else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
