/*
 * Generated by asn1c-1.0.0 (http://lionet.info/asn1c)
 * Modified for OAI compatibility - uses proper union for value field
 */

#ifndef	_X2AP_InitiatingMessage_H_
#define	_X2AP_InitiatingMessage_H_

#include <asn_application.h>
#include "X2AP_ProcedureCode.h"
#include "X2AP_Criticality.h"
#include "constr_SEQUENCE.h"
#include "X2AP_oai_compat.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations for message types */
struct X2AP_ENDCX2SetupRequest;
struct X2AP_HandoverCancel;
struct X2AP_HandoverRequest;
struct X2AP_SeNBAdditionRequest;
struct X2AP_SgNBAdditionRequest;
struct X2AP_SgNBReconfigurationComplete;
struct X2AP_SgNBReleaseRequest;
struct X2AP_SgNBReleaseRequired;
struct X2AP_UEContextRelease;
struct X2AP_X2SetupRequest;

/* X2AP_InitiatingMessage value */
typedef struct X2AP_InitiatingMessage_value {
	long present;	/* discriminator */
	union X2AP_InitiatingMessage_value_u {
		X2AP_ENDCX2SetupRequest_t	 ENDCX2SetupRequest;
		X2AP_HandoverCancel_t	 HandoverCancel;
		X2AP_HandoverRequest_t	 HandoverRequest;
		X2AP_SeNBAdditionRequest_t	 SeNBAdditionRequest;
		X2AP_SgNBAdditionRequest_t	 SgNBAdditionRequest;
		X2AP_SgNBReconfigurationComplete_t	 SgNBReconfigurationComplete;
		X2AP_SgNBReleaseRequest_t	 SgNBReleaseRequest;
		X2AP_SgNBReleaseRequired_t	 SgNBReleaseRequired;
		X2AP_UEContextRelease_t	 UEContextRelease;
		X2AP_X2SetupRequest_t	 X2SetupRequest;
	} choice;
	asn_struct_ctx_t _asn_ctx;
} X2AP_InitiatingMessage_value_t;

/* X2AP_InitiatingMessage */
typedef struct X2AP_InitiatingMessage {
	X2AP_ProcedureCode_t	 procedureCode;
	X2AP_Criticality_t	 criticality;
	X2AP_InitiatingMessage_value_t	 value;
	asn_struct_ctx_t _asn_ctx;
} X2AP_InitiatingMessage_t;

/* PR enum for value.present */
typedef enum X2AP_InitiatingMessage__value_PR {
	X2AP_InitiatingMessage__value_PR_NOTHING,
	X2AP_InitiatingMessage__value_PR_ENDCX2SetupRequest,
	X2AP_InitiatingMessage__value_PR_HandoverCancel,
	X2AP_InitiatingMessage__value_PR_HandoverRequest,
	X2AP_InitiatingMessage__value_PR_SeNBAdditionRequest,
	X2AP_InitiatingMessage__value_PR_SgNBAdditionRequest,
	X2AP_InitiatingMessage__value_PR_SgNBReconfigurationComplete,
	X2AP_InitiatingMessage__value_PR_SgNBReleaseRequest,
	X2AP_InitiatingMessage__value_PR_SgNBReleaseRequired,
	X2AP_InitiatingMessage__value_PR_UEContextRelease,
	X2AP_InitiatingMessage__value_PR_X2SetupRequest,
} X2AP_InitiatingMessage__value_PR_t;

extern asn_TYPE_descriptor_t asn_DEF_X2AP_InitiatingMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _X2AP_InitiatingMessage_H_ */
#include <asn_internal.h>
